name: ${CONTAINER_NAME}

services:
    ##############################################################################
    # Shell
    ##############################################################################
    terminal:
        image: ${TERMINAL_IMAGE_NAME}
        profiles: ["term"]
        container_name: ${CONTAINER_NAME}_env_term
        env_file:
            - ${REPO_ROOT}/.env
        command:
            - sh
            - -c
            - |
              [ -n "$$GIT_USER_NAME" ] && git config --global user.name "$$GIT_USER_NAME"
              exec zsh
        stdin_open: true
        tty: true
        working_dir: "/project"
        volumes:
            - ${REPO_ROOT}:/project
            - ${CACHE_PATH}/.npm:/root/.npm
            - ${CACHE_PATH}/.oh-my-zsh/log:/root/.oh-my-zsh/log
            - ${CACHE_PATH}/.config/gh:/root/.config/gh
            - ${CACHE_PATH}/.gitconfig:/root/.gitconfig-vol
            - ${CACHE_PATH}/.zsh:/root/.zsh-vol
        environment:
            INSIDE_DEV_CONTAINER: "true"
            GIT_CONFIG_GLOBAL: "/root/.gitconfig-vol/config"
            HISTFILE: "/root/.zsh-vol/.zsh_history"
            DEV_WORKSPACE_VERSION: "1.3.5"
    ##############################################################################
    # Tests
    ##############################################################################
    db_test:
        image: mariadb:latest
        profiles: ["test"]
        container_name: ${CONTAINER_NAME}_env_db_test
        env_file:
            - ${REPO_ROOT}/.env
        restart: always
        environment:
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress
            MARIADB_ROOT_PASSWORD: root
        ports:
          - "${DB_TESTS_PORT:-3311}:3306"
        volumes:
            - ${CACHE_PATH}/db_test:/var/lib/mysql
            - ${CACHE_PATH}/logs/db_test:/var/log/mysql
            - ./wp/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping", "-u", "root", "--password=root"]
            start_period: 30s
            interval: 5s
            retries: 10
    wp_test:
        profiles: ["test"]
        image: publishpress/dev-workspace-wordpress:wordpress-6.9-php-8.5
        container_name: ${CONTAINER_NAME}_env_wp_test
        env_file:
            - ${REPO_ROOT}/.env
        restart: always
        environment:
            WORDPRESS_DB_HOST: db_test
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: true
        ports:
            - "${WP_TESTS_HTTP_PORT:-8011}:80"
        volumes:
          - ${CACHE_PATH}/wp_test:/var/www/html/
          - ../../../../:/var/www/html/wp-content/plugins/${PLUGIN_SLUG:-}
          - ./wp/wordpress/conf.d/98-xdebug.ini:/usr/local/etc/php/conf.d/98-xdebug.ini
          - ./wp/wordpress/conf.d/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini
        depends_on:
            db_test:
                condition: service_healthy
            mailhog:
                condition: service_started
        links:
            - db_test
            - mailhog
        healthcheck:
            test: ["CMD", "test", "-f", "/var/www/html/wp-config.php"]
            start_period: 120s
            interval: 5s
            retries: 10
        extra_hosts:
            - "host.docker.internal:host-gateway"
    wp_test_cli:
        image: publishpress/dev-workspace-wpcli:wpcli-2-php-8.5
        profiles: ["test"]
        container_name: ${CONTAINER_NAME}_env_wp_test_cli
        env_file:
            - ${REPO_ROOT}/.env
        environment:
            WORDPRESS_DB_HOST: db_test
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ${CACHE_PATH}/wp_test:/var/www/html/
            - ../../../../:/var/www/html/wp-content/plugins/${PLUGIN_SLUG:-}
            - ./wp/wpcli/prepare-wp.sh:/tmp/prepare-wp.sh
            - ./wp/wpcli/conf.d/my.cnf:/tmp/my.cnf
            - ./wp/wordpress/conf.d/98-xdebug.ini:/usr/local/etc/php/conf.d/98-xdebug.ini
            - ./wp/wordpress/conf.d/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini
        depends_on:
            wp_test:
                condition: service_started
            db_test:
                condition: service_healthy
            mailhog:
                condition: service_started
        links:
            - wp_test
            - db_test
            - mailhog
        working_dir: /var/www/html
        command: ["/bin/sh", "-c", "sh /tmp/prepare-wp.sh http://localhost:${WP_TESTS_HTTP_PORT:-8011} plugin-free-wp_test"]
        extra_hosts:
            - "host.docker.internal:host-gateway"

    ##############################################################################
    # Mailhog
    ##############################################################################
    mailhog:
        image: mailhog/mailhog:latest
        profiles: ["dev", "test"]
        container_name: ${CONTAINER_NAME}_env_mailhog
        env_file:
            - ${REPO_ROOT}/.env
        ports:
            - "${MAILHOG_WEB_PORT:-8013}:8025" # Web UI
            - "${MAILHOG_SMTP_PORT:-8014}:1025" # SMTP server
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/maildir
        volumes:
            - ${CACHE_PATH}/mailhog/maildir:/maildir
        restart: always
        user: root


